### ISSUE TITLE
This code flow does not work as intended

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/QuizzMaker#10]
https://github.com/nsofiia/QuizzMaker/blob/3e0ea770ca53ee64875934639e4a1a1dad40da6c/Program.cs#L37-L42

After the user has created some questions it seems like you want to start the quiz, but since the code for this is in an else branch of the already executed condition this does not work.

Also, if you have an if () - return statement you don't really need an else, because everything will either not reach the code or reach the code so you could just write
```
if (condition)
  return;

// code just continues here
```

**Comment by nsofiia** [comment]
@incredibleLeitman 
I am jumping to the following else statement using following code
when I remove it - program is not opening the saved questions any more
<img width="282" alt="Screen Shot 2023-01-07 at 2 35 27 PM" src="https://user-images.githubusercontent.com/88280676/211169447-e9230c0c-63ac-462b-b7c5-d0439383f08a.png">

**Comment by nsofiia** [comment]
@incredibleLeitman 
this doesn't work, the program exits instead of getting the saved questions from file
<img width="247" alt="Screen Shot 2023-01-07 at 2 40 19 PM" src="https://user-images.githubusercontent.com/88280676/211169583-01baad92-8ba4-4247-b508-9dff1a6de768.png">

**Comment by incredibleLeitman** [comment]
Yes, this is the main point for this issue, this happened before too ☝️ 

Inside your if branch you change the value of the condition but never check it again:
```
if (createNewQuestion == 'Q')
{
  // do your question adding
  createNewQuestion = 'T'; // although this changes the value of the condition it is not checked ever again (only to leave your while loop)
}
// this else condition is not evaluated after the true-path was already executed
else
{
  // play the game
}
```

**Comment by nsofiia** [comment]
@incredibleLeitman you are right, I took a broader look at the code and saw it. Thank you
