### ISSUE TITLE
Is the "fileXml" param really needed?

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/QuizzMaker#4]
https://github.com/nsofiia/QuizzMaker/blob/3e0ea770ca53ee64875934639e4a1a1dad40da6c/Logic.cs#L17

If you only use the XmlSerializer in this file, you can just create it here (like the path) and don't need to provide it as parameter
(same goes for RetrieveDataFromXml function)

**Comment by nsofiia** [comment]
@incredibleLeitman 
doesn't work, I tried a couple of ways
<img width="630" alt="Screen Shot 2023-01-07 at 1 09 13 PM" src="https://user-images.githubusercontent.com/88280676/211166767-f6ce15f8-c67b-4440-b5a7-7507bc56003e.png">
<img width="594" alt="Screen Shot 2023-01-07 at 1 09 35 PM" src="https://user-images.githubusercontent.com/88280676/211166769-25e4c475-e2db-4328-a8ed-69f5dc0c2e31.png">

not sure how

**Comment by incredibleLeitman** [comment]
Did you create/move the "xml" variable?

In case you want the variable have accessible without having to create the containing class itself with new you want to make it static. This also makes that the variable exists only once. 
You could also make it readonly because you don't ever change it
```static readonly XmlSerializer xml = new XmlSerializer(typeof(List<Question>));```

**Comment by nsofiia** [comment]
@incredibleLeitman it worked with static keyword! thank you
