### ISSUE TITLE
Do you really need the "list" parameter?

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/QuizzMaker#5]
https://github.com/nsofiia/QuizzMaker/blob/3e0ea770ca53ee64875934639e4a1a1dad40da6c/Logic.cs#L31

You provide a parameter for the list of questions, but in case the file exists you just override it,
and in case something went wrong you just return the same parameter.

It would be better to create the list inside your function, if the file exists fill it, otherwise return the created empty list

**Comment by nsofiia** [comment]
@incredibleLeitman 

is this what I needed to do ?
removed list from parameters,
creating new lost inside the method and returning it 

<img width="680" alt="Screen Shot 2023-01-07 at 1 18 18 PM" src="https://user-images.githubusercontent.com/88280676/211167047-25e35de7-14d6-4786-b61a-68139432a49c.png">
