### ISSUE TITLE
refactor AnswersAddOrder

### ISSUE THREAD

**Issue by incredibleLeitman** [nsofiia/QuizzMaker#6]
https://github.com/nsofiia/QuizzMaker/blob/3e0ea770ca53ee64875934639e4a1a1dad40da6c/Logic.cs#L49-L76

This function has a lot of flaws:
- if you have a constant list of characters you want to prepend every time you call the function, this variable also should be a constant
- but anyway, if you support multiple answers I would suggest instead of prepending a letter you just use an index, this will allow you to remove some of the additional handling
- checking if "if (answer.Length == 1 && answer.Contains(' ')) " only catches a few cases where the answer is valid, for example if the user entered two whitespaces or a tab this would not trigger. Instead you could use String.IsNullOrWhitespace https://learn.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=net-7.0
- the checking if the answer is even valid should not happen when you trying to print it but already after the user has entered them.

**Comment by nsofiia** [comment]
@incredibleLeitman 

1st point - cool
2nd - I want my answers to be printed with letters on purpose, I want it to look like a real test with abc answers
3rd - cool
4th - i will have to rewrite how I handle the answers input to add answers check right away. In this method I am splitting bulk of answers into a list and removing empty answers for them not to be printed


is this ok?
<img width="515" alt="Screen Shot 2023-01-07 at 1 44 33 PM" src="https://user-images.githubusercontent.com/88280676/211167882-e9db8f6a-b803-4397-be41-d189be4427c7.png">

**Comment by incredibleLeitman** [comment]
2. point: oh ok, if you want it like that way and can deal with the extra effort this is also ok for me 👍 
 One drawback for example would be, that the number of given answers could in theory exceed the amount of letters, although this is a very rare case ^^

4.: I think the function is ok, although the index should only be increased when adding a valid answer, otherwise you can have something like A, B, D for example if the third answers was an empty string.
But still, this functionality should belong, where the user enters the answers. Otherwise you already store "invalid" answers in your xml, load it and have to additionally process those invalid answers to make it look correct in the console
